### ISSUE TITLE
Create Installation and Usage section in README

### ISSUE THREAD

**Issue by seveibar** [kgram/react-equation#2]
I'm interested in using this project, but it's missing usage and installation sections in the README

**Comment by kgram** [comment]
Yeah, sorry about that, I've been working on it on and off when I have a minute to spare, but always on the fun parts. You know how it is. Knowing someone is interested in using it is a good motivating factor though, I'll take a crack at getting the last bits finished and writing some documentation.

You may be interested to know that I've done a major rewrite since the version published on npm. The parsing and resolving has been moved to separate projects ([equation-parser](https://www.npmjs.com/package/equation-parser) and [equation-resolver](https://www.npmjs.com/package/equation-resolver), though they are equally undocumented), removed the parsers dependency on nearley and improved the handling of errors.

**Comment by kgram** [comment]
There you are, hopefully that is sufficient 🙂 

If anything is still confusing, please let me know. If you do end up using it for something, I'd love to see it, and maybe get some feedback on the project.
