### ISSUE TITLE
Get result value of equation

### ISSUE THREAD

**Issue by jsandrea88** [kgram/react-equation#21]
Hello, this project is incredible, but I would like to know if there is any way to capture the result of the evaluation of the equation in a variable.

**Comment by kgram** [comment]
Not directly in react, although if you can think of a good API for doing so I'd be happy to implement it. Maybe something with refs could work. Doing it with context would have lots of problems, since if you add an equation at the top of the page, the context provider would have no way of knowing it shouldn't have access to all later variables.

Anyways, what you can do is jump a bit into the underlying packages, `equation-parser` and `equation-resolver`. If you take over the parsing and resolving, you can control the order things happen in. [Here's an example I used during development in storybook, adapted to codesandbox.](https://codesandbox.io/s/angry-antonelli-x6v7h0?file=/src/MultilineEquation.tsx:1048-1373). It manually parses and evaluates a list of equations, and then use `EquationPreparsed` to render them. Variable and function assignments are detected and available for later equations.

Without knowing any details of what you're doing, I can't come much closer than that.

I know this might look a bit abandoned (well, maybe it _is_ a bit abandoned), but if you need any new functionality and find any bugs, I'll be happy to take a look (the same goes for `equation-parser` and `equation-resolver`).

**Comment by jsandrea88** [comment]
Hello @kgram, thanks for your answer and your example, it will be useful to me.

Well, using your project, I tried to get the value of the result using ref, but I couldn't find any property or variable to get it.

What I'm doing is a simple equation, eg (m - a * 1) / 2 + 1220001.11111 / 3.14, and it works fine for that, but I also need to get the value to store it.

It would be nice to also have a way to change for example the length of the result in number, for my test equation I get the result `3.89⋅10^5` when I need something like `388536.3857038216`

![image](https://user-images.githubusercontent.com/21974052/161060922-4ea3e9d1-a86d-444b-82e1-804331a6183c.png)

**Comment by kgram** [comment]
Both things sounds doable. I'll look into it 🙂

**Comment by kgram** [comment]
I just pushed 1.0.0-rc.1 of `react-equation` and `equation-resolver`. It should fix both issues.

All the equation-components now expose a ref with all their calculated parts. You'll want `result` if you need to use it elsewhere. Here's an example that just logs the ref out.

https://codesandbox.io/s/react-equation-example-forked-swiueq?file=/src/index.js

Formatting a result now allows a `decimals` options for controlling how numbers are rendered. Not sure it's the best naming, though. Here's a couple of examples:

https://codesandbox.io/s/react-equation-example-forked-yi8nj9?file=/src/index.js

I'm gonna upgrade dependencies and maybe polish things a bit up before releasing a full 1.0.0, but see if this solves your problem.

**Comment by jsandrea88** [comment]
Hi @kgram.

I have been testing it and it works smoothly and very well.

What a good job you've done here. Thank you.
